#!/usr/bin/env python3
"""Generate a final Markdown interpretation report from workflow outputs."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate final interpretation report.")
    parser.add_argument("--workflow-dir", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=Path("results/25_final_interpretation_summary.md"))
    parser.add_argument("--min-enrichment-edges", type=int, default=25)
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def require(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Required input not found: {path}")


def top_by(rows: list[dict[str, str]], key: str, reverse: bool = True, limit: int = 5) -> list[dict[str, str]]:
    return sorted(rows, key=lambda row: float(row[key]), reverse=reverse)[:limit]


def reliable_enrichment_rows(rows: list[dict[str, str]], min_edges: int) -> list[dict[str, str]]:
    reliable = [row for row in rows if int(row["edge_count"]) >= min_edges]
    return reliable if reliable else rows


def category_dominant_phenotypes(composition_rows: list[dict[str, str]]) -> dict[str, dict[str, str]]:
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in composition_rows:
        grouped[row["category"]].append(row)
    return {category: top_by(rows, "fraction", True, 1)[0] for category, rows in grouped.items()}


def write_report(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> None:
    args = parse_args()
    workflow_dir = args.workflow_dir.resolve()
    results = workflow_dir / "results"

    required_files = {
        "feature_summary": results / "11_processed_single_cell_features_summary.csv",
        "qc_summary": results / "12_processed_single_cell_qc_summary.csv",
        "composition_category": results / "15_phenotype_composition_by_category.csv",
        "interaction_summary": results / "19_spatial_phenotype_interaction_summary.csv",
        "enrichment_category": results / "21_spatial_phenotype_enrichment_by_category.csv",
        "plasma_summary": results / "24_plasma_cell_niche_summary.csv",
    }
    for input_path in required_files.values():
        require(input_path)

    feature_summary = {row["metric"]: row["value"] for row in read_csv(required_files["feature_summary"])}
    qc_summary = {row["metric"]: row["value"] for row in read_csv(required_files["qc_summary"])}
    composition_category = read_csv(required_files["composition_category"])
    interaction_summary = {row["metric"]: row["value"] for row in read_csv(required_files["interaction_summary"])}
    enrichment_category = read_csv(required_files["enrichment_category"])
    plasma_summary = read_csv(required_files["plasma_summary"])

    dominant = category_dominant_phenotypes(composition_category)
    ranked_enrichment_rows = reliable_enrichment_rows(enrichment_category, args.min_enrichment_edges)
    top_enriched = top_by(ranked_enrichment_rows, "log2_enrichment", True, 8)
    top_depleted = top_by(ranked_enrichment_rows, "log2_enrichment", False, 8)
    unknown_rows = [row for row in composition_category if row["phenotype"] == "Unknown"]
    unknown_fractions = [float(row["fraction"]) for row in unknown_rows]
    mean_unknown_fraction = sum(unknown_fractions) / len(unknown_fractions) if unknown_fractions else 0.0

    lines: list[str] = []
    lines.append("# Final Interpretation Summary")
    lines.append("")
    lines.append("## Scope")
    lines.append("")
    lines.append(
        "This report summarizes the current reproducible IMC analysis workflow from exported "
        "single-cell features through rule-based phenotyping, spatial interaction analysis, "
        "spatial enrichment, and plasma-cell-focused niche interpretation."
    )
    lines.append("")
    lines.append("The conclusions are exploratory because phenotype labels are generated by transparent rule-based approximation rather than expert-reviewed annotation or supervised classification.")
    lines.append("")
    lines.append("## Technical Summary")
    lines.append("")
    lines.append(f"- Input cells before feature filtering: `{feature_summary.get('input_cells', 'NA')}`")
    lines.append(f"- Retained cells after area filtering: `{feature_summary.get('retained_cells_after_area_filter', 'NA')}`")
    lines.append(f"- Removed cells with area below threshold: `{feature_summary.get('removed_cells_area_lt_min_area', 'NA')}`")
    lines.append(f"- Marker columns processed: `{feature_summary.get('marker_columns_processed', 'NA')}`")
    lines.append(f"- Images represented after processing: `{qc_summary.get('image_count', 'NA')}`")
    lines.append(f"- Minimum retained object area: `{qc_summary.get('minimum_area', 'NA')}` pixels")
    lines.append(f"- Unique undirected spatial edges considered: `{interaction_summary.get('unique_undirected_edges', 'NA')}`")
    lines.append(f"- Minimum edge count used for ranked enrichment interpretation: `{args.min_enrichment_edges}`")
    lines.append("")
    lines.append("## Phenotype Composition")
    lines.append("")
    lines.append("Dominant rule-based phenotype by category:")
    lines.append("")
    lines.append("| Category | Dominant phenotype | Cell count | Fraction |")
    lines.append("|---|---|---:|---:|")
    for category in sorted(dominant):
        row = dominant[category]
        lines.append(f"| {category} | {row['phenotype']} | {row['cell_count']} | {float(row['fraction']):.3f} |")
    lines.append("")
    lines.append("Interpretation: dominant phenotypes provide a first-pass summary of dataset composition. Large `Unknown` fractions indicate that conservative rules leave many cells unassigned and that future annotation refinement is warranted.")
    lines.append("")
    lines.append("## Spatial Enrichment")
    lines.append("")
    lines.append(f"Top enriched phenotype-neighbor pairs by category with at least `{args.min_enrichment_edges}` edges:")
    lines.append("")
    lines.append("| Category | Phenotype A | Phenotype B | Edges | log2 enrichment |")
    lines.append("|---|---|---|---:|---:|")
    for row in top_enriched:
        lines.append(
            f"| {row['category']} | {row['phenotype_a']} | {row['phenotype_b']} | "
            f"{row['edge_count']} | {float(row['log2_enrichment']):.3f} |"
        )
    lines.append("")
    lines.append(f"Top depleted phenotype-neighbor pairs by category with at least `{args.min_enrichment_edges}` edges:")
    lines.append("")
    lines.append("| Category | Phenotype A | Phenotype B | Edges | log2 enrichment |")
    lines.append("|---|---|---|---:|---:|")
    for row in top_depleted:
        lines.append(
            f"| {row['category']} | {row['phenotype_a']} | {row['phenotype_b']} | "
            f"{row['edge_count']} | {float(row['log2_enrichment']):.3f} |"
        )
    lines.append("")
    lines.append("Interpretation: positive log2 enrichment indicates adjacency above abundance expectation, whereas negative values indicate depletion relative to abundance expectation. Ranked tables apply a minimum edge-count threshold so that very rare one-off adjacencies do not dominate the final narrative.")
    lines.append("")
    lines.append("## Plasma-Cell-Like Spatial Niche")
    lines.append("")
    lines.append("Plasma-cell-like niche summary by category:")
    lines.append("")
    lines.append("| Category | Plasma-cell-like fraction | Top enriched neighbor | Edges | log2 | Top depleted neighbor | Edges | log2 |")
    lines.append("|---|---:|---|---:|---:|---|---:|---:|")
    for row in plasma_summary:
        lines.append(
            f"| {row['category']} | {float(row['plasma_cell_fraction']):.3f} | "
            f"{row['top_enriched_neighbor']} | {row.get('top_enriched_edges', 'NA')} | "
            f"{float(row['top_enriched_log2']):.3f} | "
            f"{row['top_depleted_neighbor']} | {row.get('top_depleted_edges', 'NA')} | "
            f"{float(row['top_depleted_log2']):.3f} |"
        )
    lines.append("")
    lines.append("Interpretation: plasma-cell-like neighbor enrichment identifies the approximate phenotypes that occur near plasma-cell-like cells more or less often than expected from abundance. This is the most study-aligned exploratory analysis currently implemented because the template paper centers on plasma-cell spatial niches.")
    lines.append("")
    lines.append("## Overall Conclusion")
    lines.append("")
    lines.append(
        "The current workflow successfully converts representative raw IMC data into segmented cells, "
        "processed single-cell marker features, rule-based phenotype labels, spatial neighbor summaries, "
        "abundance-normalized spatial enrichment tables, and plasma-cell-focused niche summaries."
    )
    lines.append("")
    lines.append(
        "The data support an exploratory interpretation of phenotype composition and spatial organization "
        "within the representative subset. Plasma-cell-like spatial niche outputs provide the most direct "
        "connection to the biological focus of the template study, while enrichment tables help distinguish "
        "high raw interaction counts from adjacency patterns that exceed abundance expectation."
    )
    if mean_unknown_fraction > 0.25:
        lines.append("")
        lines.append(
            "A substantial fraction of cells remains `Unknown`, indicating that the final interpretation is "
            "best viewed as a technical and exploratory biological summary until phenotype annotation is "
            "validated or replaced with a reference-guided classifier."
        )
    lines.append("")
    lines.append("## Limitations")
    lines.append("")
    lines.append("- Rule-based phenotyping is not equivalent to expert annotation, XGBoost classification, or FlowSOM review.")
    lines.append("- Current spatial enrichment uses an abundance-based expectation, not a permutation-based null model.")
    lines.append("- The representative subset is small and should not be used for final biological claims.")
    lines.append("- Bone-distance and CellCharter-style neighborhood analyses are not yet implemented in this simplified workflow.")
    lines.append("")
    lines.append("## Recommended Next Development")
    lines.append("")
    lines.append("A future extension should add either reference-guided phenotype validation or permutation-based spatial enrichment testing. Bone-mask integration can be added if reproducible bone annotations are available for the target dataset.")
    lines.append("")

    output_path = workflow_dir / args.output
    write_report(output_path, "\n".join(lines))
    print(f"Final interpretation report: {output_path}")


if __name__ == "__main__":
    main()
